name: Build x86_64 and aarch64 Mercury

on:
  # Exclude all branches from push events.
  push:
    branches: '!**'
  # Exclude all branches from pull_request events.
  pull_request:
    branches: '!**'
  # Allow a workflow to be run manually.
  workflow_dispatch:

env:
  MERCURY_ROTD: '2024-02-27'

jobs:
  build-mercury:
    name: Build x86_64 and aarch64 Mercury
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
      with:
        clean: true

    - name: Run build script
      run: ./bin/install-then-build.sh

    - name: Upload aarch64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: mercury-rotd-${{ env.MERCURY_ROTD }}-aarch64-apple-darwin
        path: output/mercury-rotd-${{ env.MERCURY_ROTD }}-aarch64-apple-darwin.tar.gz

    - name: Upload x86_64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: mercury-rotd-${{ env.MERCURY_ROTD }}-x86_64-apple-darwin
        path: output/mercury-rotd-${{ env.MERCURY_ROTD }}-x86_64-apple-darwin.tar.gz
